export const GET_DATA_REQ = "GET_DATA_REQ"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_FAIL = "GET_DATA_FAIL"

export const GET_SINGLE_DATA_REQ = "GET_SINGLE_DATA_REQ"
export const GET_SINGLE_DATA_SUCCESS = "GET_SINGLE_DATA_SUCCESS"
export const GET_SINGLE_DATA_FAIL = "GET_SINGLE_DATA_FAIL"

export const ADD_TO_CART = "ADD_TO_CART"
export const GET_CART = "GET_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const CHANGE_QTY = "CHANGE_QTY" 